CREATE TABLE GESTLOG_ROTAS (
    ID_ROTA         NUMBER PRIMARY KEY,
    DESCRICAO_ROTA  VARCHAR2(255),
    BAIRRO_ROTA_1   VARCHAR2(100),
    BAIRRO_ROTA_2   VARCHAR2(100),
    BAIRRO_ROTA_3   VARCHAR2(100),
    BAIRRO_ROTA_4   VARCHAR2(100),
    BAIRRO_ROTA_5   VARCHAR2(100),
    COD_MOTORISTA   NUMBER,
    COD_VEICULO     NUMBER,
    DATA_ROTA       DATE,
    CODUSUR_CRIACAO NUMBER,
    DATA_CRIACAO DATE,
    TURNO_SEPARACAO VARCHAR2 (1)
);