CREATE TABLE GESTLOG_ROTAS_PEDIDOS (
    ID_ITEM       NUMBER PRIMARY KEY,
    ID_ROTA       NUMBER,
    NUMPED        NUMBER,
    CODUSUR_ADD   NUMBER,
    DATA_ADD      DATE,
    CONSTRAINT FK_ROTA
    FOREIGN KEY (ID_ROTA)
    REFERENCES GESTLOG_ROTAS(ID_ROTA)
);