CREATE TABLE GESTLOG_VEICULOS (
    ID                 NUMBER(10)        PRIMARY KEY,
    DESCRICAO_VEICULO  VARCHAR2(150),
    PLACA_VEICULO      VARCHAR2(10),
    DATA_CRIACAO       DATE              DEFAULT SYSDATE,
    CODUSUR_CRIACAO    NUMBER(10),
    CAPACIDADE_CIMENTO NUMBER DEFAULT 0 NOT NULL
);